# cluster_config.yml - cluster configuration
__default__:
  account: your-lab
  partition: serial
  time: 08:00:00
  cpus-per-task: 2
  mem: 16G
  output: logs/slurm-%x.%A.%a.log

fastqc_raw:
  cpus-per-task: 4
  mem: 32G
  cores: 4
  time: 02:00:00
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

trim_adapters:
  cpus-per-task: 8
  mem: 32G
  cores: 8
  ...
  
align_spom:
  cpus-per-task: 16
  mem: 64G
  cores: 16
  ...
  
