## samples file
samples_csv: "config/samples.csv"

# ==============================================================================
# GENOME and BLACKLIST PATHS
# ==============================================================================

# Primary (no spike-in) genome = S. cerevisiae
scer_genome: "/s/cobre-dev-bio/boydk/Rafal_Lab/saccharomyces_cerevisiae_scer_genome/SGD_R64-3-1_genome_bowtie2_index/SGD_R64-3-1_genome"
blacklist_scer: "/s/cobre-dev-bio/boydk/Rafal_Lab/saccharomyces_cerevisiae_scer_genome/SGD_R64-3-1_blacklist.bed"
genome_file_scer: "/s/cobre-dev-bio/boydk/Rafal_Lab/saccharomyces_cerevisiae_scer_genome/SGD_R64-3-1_genomefile.txt"

# Default spike-in genome = D. melanogaster
spikein_genome: "/s/cobre-dev-bio/boydk/Rafal_Lab/drosophila_melanogaster_dmel_genome/NCBI_R6plusISO1MT_genome_bowtie2_index/NCBI_R6plusISO1MT_genome"

# ------------------------------------------------------------------------------
# Optionally, if you want to switch to S. pombe as spike-in, change spikein_genome with specified path found below:
# spom
# spom_genome: "/s/cobre-dev-bio/boydk/Rafal_Lab/schizosaccharomyces_pombe_spom_genome/NCBI_ASM294v2_genome_bowtie2_index/NCBI_ASM294v2_genome"
# genome_file_spom: "/s/cobre-dev-bio/boydk/Rafal_Lab/schizosaccharomyces_pombe_spom_genome/NCBI_ASM294v2_genomefile.txt"
# dmel
# dmel_genome: "/s/cobre-dev-bio/boydk/Rafal_Lab/drosophila_melanogaster_dmel_genome/NCBI_R6plusISO1MT_genome_bowtie2_index/NCBI_R6plusISO1MT_genome"
# ------------------------------------------------------------------------------

# ==============================================================================
# ADAPTER FILE (BBDuk)
# ==============================================================================
bbmap_ref: "/s/cobre-dev-bio/boydk/Rafal_Lab/adapters/truseq_universal_adapters.fa"

# ==============================================================================
# BIGWIG / DEEPTOOLS PARAMETERS
# ==============================================================================
binSize: 1

# ==============================================================================
# SOFTWARE MODULE VERSIONS
# ==============================================================================
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
bbmap: "bbmap/39.06"
bowtie2: "bowtie2/2.5.0"
samtools: "samtools/1.18"
deeptools: "deeptools/3.5.4"
bedtools: "bedtools/2.30.0"
ucsc: "ucsc/20200225"
python: "python/3.10.2"
