# ==============================================================================
# SAMPLES FILE
# ==============================================================================
samples_csv: "config/samples.csv"

# ==============================================================================
# PRIMARY GENOME & BLACKLIST FILE PATHS
# ==============================================================================
# Primary genome = S. cerevisiae
primary_bowtie_genome: "/hpc-prj/donczew/genomic_resources/Scerevisiae_GCF_000146045.2/SGD_R64-3-1_genome_bowtie2_index/SGD_R64-3-1_genome"
primary_genome_file: "/hpc-prj/donczew/genomic_resources/Scerevisiae_GCF_000146045.2/SGD_R64-3-1_genomefile.txt"
# blacklist and include list
blacklist: "/hpc-prj/donczew/genomic_resources/Scerevisiae_GCF_000146045.2/SGD_R64-3-1_excludelist.bed"
include_list: "/hpc-prj/donczew/genomic_resources/Scerevisiae_GCF_000146045.2/SGD_R64-3-1_includelist.bed"

# ==============================================================================
# TOGGLE ON/OFF ALIGNMENT FILTERING
# ==============================================================================
use_filtering: true

# ==============================================================================
# SPIKE IN GENOME
# ==============================================================================
# Default spike-in genome = S. pombe
spikein_genome: "/hpc-prj/donczew/genomic_resources/Spombe_GCF_000002945.1/NCBI_ASM294v2_genome_bowtie2_index/NCBI_ASM294v2_genome"

# ------------------------------------------------------------------------------
# Optionally, if you want to switch to D. melanogaster as spike-in, change spikein_genome with specified path found below:
# spom
# spom_genome: "/hpc-prj/donczew/genomic_resources/Spombe_GCF_000002945.1/NCBI_ASM294v2_genome_bowtie2_index/NCBI_ASM294v2_genome"
# dmel
# dmel_genome: "/hpc-prj/donczew/genomic_resources/Dmelanogaster_GCF_000001215.4/NCBI_R6plusISO1MT_genome_bowtie2_index/NCBI_R6plusISO1MT_genome"
# ------------------------------------------------------------------------------

# ==============================================================================
# TOGGLE ON/OFF TRIM GALORE (false = BBDuk | true = Trim Galore)
# ==============================================================================
use_trim_galore: false
# BBDuk adapter file
bbmap_ref: "/hpc-prj/donczew/genomic_resources/bbmap/truseq_universal_adapters.fa"
# Trim Galore parameters
stringency: 3
length: 10

# ==============================================================================
# BIGWIG / DEEPTOOLS PARAMETERS
# ==============================================================================
binSize: 1

# ==============================================================================
# SOFTWARE MODULE VERSIONS
# ==============================================================================
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
bbmap: "bbmap/39.06"
trim_galore: "trim_galore/0.6.7"
bowtie2: "bowtie2/2.5.0"
samtools: "samtools/1.18"
deeptools: "deeptools/3.5.4"
bedtools: "bedtools/2.30.0"
ucsc: "ucsc/20200225"
python: "python/3.10.2"
R: "R/4.4.1-mkl"
