## samples file
samples_csv: "config/samples.csv"

# Genome indices
spom_genome: "/path/to/spombe_bowtie2_index/spombe"
dmel_genome: "/path/to/dmelanogaster_bowtie2_index/dmel"

# Blacklist (if you have one for spom)
blacklist_spom: "/path/to/spombe_blacklist.bed"

# bbmap adapter file (used by BBDuk)
bbmap_ref: "/path/to/bbmap/truseq_universal_adapters.fa"

# Genome file (for bigWig creation via bedGraphToBigWig)
genome_file_spom: "/path/to/spombe/genomefile.txt"

# binSize, normalization, etc.
binSize: 1

# Module versions (example - adapt to your HPC)
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
bbmap: "bbmap/39.06"
bowtie2: "bowtie2/2.5.0"
samtools: "samtools/1.18"
deeptools: "deeptools/3.5.4"
bedtools: "bedtools/2.30.0"
ucsc: "ucsc/20200225"
python: "python/3.10.2"
